# Generated by Django 5.0.7 on 2024-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Culture', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
