# Generated by Django 5.0.7 on 2024-12-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the event', max_length=200)),
                ('description', models.TextField(help_text='A brief description of the event')),
                ('image', models.ImageField(help_text='Event image', upload_to='event_images/')),
                ('link', models.URLField(default='#', help_text='Link to event details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event was created')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
