# Generated by Django 5.0.7 on 2024-12-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_latestevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEventHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event highlight video', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the video')),
                ('image', models.ImageField(help_text='Upload video thumbnail image', upload_to='highlight_images/')),
                ('video_link', models.URLField(help_text='Link to the video details page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'ordering': ['-created_at'],
            },
        ),
    ]
