# Generated by Django 5.0.7 on 2024-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_latesteventhighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the showcase item.', max_length=100)),
                ('image', models.ImageField(help_text='Upload the showcase image.', upload_to='showcase_images/')),
                ('link', models.URLField(help_text='Link to the related blog or page.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the carousel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showcase Item',
                'verbose_name_plural': 'Showcase Items',
                'ordering': ['display_order'],
            },
        ),
    ]
