# Generated by Django 5.0.7 on 2024-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the media item.', max_length=100)),
                ('description', models.TextField(help_text='Brief description of the media item.', max_length=300)),
                ('image', models.ImageField(help_text='Upload the media image.', upload_to='media_section/')),
                ('link', models.URLField(help_text='URL link to related content or blog.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the carousel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['display_order'],
            },
        ),
    ]
