# Generated by Django 5.0.7 on 2024-12-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'LatestEvents', 'verbose_name_plural': 'LatestEvents'},
        ),
        migrations.AlterModelOptions(
            name='latesteventhighlight',
            options={'ordering': ['-created_at'], 'verbose_name': 'LatestHighlight', 'verbose_name_plural': 'LatestHighlights'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['display_order'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='showcase',
            options={'ordering': ['display_order'], 'verbose_name': 'Showcase', 'verbose_name_plural': 'Showcase'},
        ),
    ]
