# Generated by Django 5.0.7 on 2024-12-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_trending_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trending_now',
            options={'ordering': ['Trend_order'], 'verbose_name': 'Trending_now', 'verbose_name_plural': 'Trending_now'},
        ),
        migrations.RenameField(
            model_name='trending_now',
            old_name='display_order',
            new_name='Trend_order',
        ),
    ]
