# Generated by Django 5.0.7 on 2024-12-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_trending_now_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featured_shows/')),
            ],
        ),
    ]
